[debug] RPM transfer failed in CentOS5 in Travis-CI
```
Disabling updates.puppetlabs.com by modifying hosts file to resolve updates to 127.0.0.1 on centos5
/home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/host.rb:330:in `exec': Host 'centos5' exited with 1 running: (Beaker::Host::CommandFailure)
 rpm --replacepkgs -ivh http://yum.puppetlabs.com/puppetlabs-release-pc1-el-5.noarch.rpm
Last 10 lines of output were:
	error: skipping http://yum.puppetlabs.com/puppetlabs-release-pc1-el-5.noarch.rpm - transfer failed - Unknown or unexpected error
	Retrieving http://yum.puppetlabs.com/puppetlabs-release-pc1-el-5.noarch.rpm
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/command_factory.rb:35:in `execute'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/host/unix/pkg.rb:142:in `install_package_with_rpm'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/dsl/install_utils/foss_utils.rb:865:in `block in install_puppetlabs_release_repo_on'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/shared/host_manager.rb:115:in `run_block_on'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/dsl/patterns.rb:35:in `block_on'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/dsl/install_utils/foss_utils.rb:839:in `install_puppetlabs_release_repo_on'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/dsl/install_utils/foss_utils.rb:358:in `block in install_puppet_agent_on'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/shared/host_manager.rb:115:in `run_block_on'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/shared/host_manager.rb:104:in `block in run_block_on'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/shared/host_manager.rb:103:in `map'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/shared/host_manager.rb:103:in `run_block_on'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/dsl/patterns.rb:35:in `block_on'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/beaker-2.37.0/lib/beaker/dsl/install_utils/foss_utils.rb:332:in `install_puppet_agent_on'
	from /home/travis/build/hfm/puppet-mha/spec/spec_helper_acceptance.rb:4:in `<top (required)>'
	from /home/travis/build/hfm/puppet-mha/spec/acceptance/mha_manager_spec.rb:1:in `require'
	from /home/travis/build/hfm/puppet-mha/spec/acceptance/mha_manager_spec.rb:1:in `<top (required)>'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<main>'
/usr/local/rvm/rubies/ruby-2.2.3/bin/ruby -I/home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/lib:/home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib /home/travis/build/hfm/puppet-mha/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.4/exe/rspec spec/acceptance --color failed
```