Use curl instead of wget
In CentOS 5, wget fails to download mha4mysql-manager's rpm with SSL.
wget in CentOS 5 may not recognize the certificates with subjectAltName.

```
$ wget -O /usr/local/src/mha4mysql-manager-0.56-0.el5.noarch.rpm "https://72003f4c60f5cc941cd1c7d448fc3c99e0aebaa8.googledrive.com/host/0B1lu97m8-haWeHdGWXp0YVVUSlk/mha4mysql-manager-0.56-0.el5.noarch.rpm"
--2016-03-24 07:28:50--  https://72003f4c60f5cc941cd1c7d448fc3c99e0aebaa8.googledrive.com/host/0B1lu97m8-haWeHdGWXp0YVVUSlk/mha4mysql-manager-0.56-0.el5.noarch.rpm
Resolving 72003f4c60f5cc941cd1c7d448fc3c99e0aebaa8.googledrive.com... 216.58.220.161, 2404:6800:4004:812::2001
Connecting to 72003f4c60f5cc941cd1c7d448fc3c99e0aebaa8.googledrive.com|216.58.220.161|:443... connected.
ERROR: certificate common name `*.googleusercontent.com' doesn't match requested host name `72003f4c60f5cc941cd1c7d448fc3c99e0aebaa8.googledrive.com'.
To connect to 72003f4c60f5cc941cd1c7d448fc3c99e0aebaa8.googledrive.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.
```

Using cURL, it solves.